releases:
- {name: prometheus, version: latest}

compilation:
  workers: 6
  network: prometheus1
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m3.xlarge
    ephemeral_disk:
      size: 30000
      type: gp2
      encrypted: true

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-600000
  update_watch_time: 1000-600000
  serial: false

resource_pools:
- name: small_z1
  network: prometheus1
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

- name: small_z1_public
  network: prometheus1
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
