cg-deploy-prometheus-git-branch: main
cg-deploy-prometheus-git-url: https://github.com/cloud-gov/cg-deploy-prometheus.git

prometheus-release-git-branch: master
prometheus-release-version-filter: v30.*
prometheus-release-git-url: https://github.com/bosh-prometheus/prometheus-boshrelease

pipeline-tasks-git-branch: main
pipeline-tasks-git-url: https://github.com/cloud-gov/cg-pipeline-tasks.git

slack-channel-success: "#cg-platform-news"
slack-news-channel: "#cg-platform-news"
slack-icon-url: https://avatars1.githubusercontent.com/u/7809479?v=3&s=40

aws-iam-prefix-delimiter: "_"
